window.CYBER_TYPE_ICONS = {
    tool: 'fa-screwdriver-wrench',
    guide: 'fa-book',
    reference: 'fa-layer-group',
    wordlist: 'fa-list',
    database: 'fa-database',
    training: 'fa-graduation-cap',
    search: 'fa-magnifying-glass',
    calculator: 'fa-calculator',
    framework: 'fa-diagram-project',
    archive: 'fa-box-archive',
    cheatsheet: 'fa-clipboard-list',
    dataset: 'fa-table',
    lab: 'fa-flask',
    paper: 'fa-file-lines',
    standard: 'fa-file-contract',
    checklist: 'fa-list-check',
    service: 'fa-cloud',
    repo: 'fa-code-branch',
    script: 'fa-code',
    plugin: 'fa-puzzle-piece',
    report: 'fa-file-circle-check',
    podcast: 'fa-podcast',
    news: 'fa-newspaper'
};
